server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/taskdb
    username: dev
    password: dev
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: bXlfc3VwZXJfc2VjcmV0X2tleV9mb3Jfanp3dF9pbl9iYXNlNjQ=
  expiration: 3600000

notification:
  service:
    url: http://localhost:8083/notifications/send

aws:
  s3:
    endpoint: http://localhost:9000
    bucket: task-attachments
  accessKey: minio
  secretKey: minio123
