server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: dev
    password: dev
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: bXlfc3VwZXJfc2VjcmV0X2tleV9mb3Jfanp3dF9pbl9iYXNlNjQ= 
  expiration: 3600000 